[package]
name = "connect-ip-rust-scion"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4", features = ["derive"] }
ipnet = { version = "2.11.0", features = ["serde"] }
metrics = "0.24.3"
metrics-exporter-prometheus = "0.18.1"
metrics-util = "0.20.1"
octets = "0.3.3"
pnet = "0.35.0"
quiche = "0.24.6"
ring = "0.17.14"
scion-proto = { git = "https://github.com/Anapaya/scion-sdk.git", rev = "4ff09c1b1621570d1f25af149f390addf15a2de6" }
scion-stack = { git = "https://github.com/Anapaya/scion-sdk.git", rev = "4ff09c1b1621570d1f25af149f390addf15a2de6" }
serde = "1.0.228"
serde_json = "1.0.149"
thiserror = "2.0.17"
tokio = { version = "1.28.1", features = ["full"] }
tokio-util = "0.7.16"
tracing = "0.1.41"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.0", default-features = false, features = ["env-filter", "fmt", "ansi", "time", "local-time"] }
tun-rs = { version = "2", features = ["async"] }
url = "2.5.7"
x509-parser = "0.18.0"
