[package]
name = "connect-ip-rust-scion"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4", features = ["derive"] }
ipnet = "2.11.0"
octets = "0.3.3"
pnet = "0.35.0"
quiche = "0.24.6"
ring = "0.17.14"
thiserror = "2.0.17"
tokio = { version = "1.28.1", features = ["full"] }
tokio-util = "0.7.16"
tracing = "0.1.41"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.0", default-features = false, features = ["env-filter", "fmt", "ansi", "time", "local-time"] }
tun-rs = { version = "2", features = ["async"] }
url = "2.5.7"
